version: "3.8"
services:
  app:
    image: periomodel:01
    container_name: periomodel
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_periomodel=1
    ipc: host
    environment:
    #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - HOME=/app
    - DATA_ROOT=/app/data
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - $HOME/data/dcmdata:/app/data